-- GENERATED by api/scripts/directory-standins.py — do not edit by hand.
-- Regenerate with `pnpm db:stubs:generate`; `pnpm db:stubs:check` proves it is current.
--
-- The slice of tic-auth's schema campus foreign-keys into and reads through.
-- Applied by `make test-db` BEFORE campus's own migrations, because a bare Postgres
-- has none of it and the migrations would not apply (F31, docs/FEATURES.md Group J).

-- Enum types, named by the columns below.
CREATE TYPE offering_kind AS ENUM ('mandatory', 'optional');
CREATE TYPE term_kind AS ENUM ('first', 'second', 'full');

-- Base tables, in dependency order.
CREATE TABLE academic_year (
	id SERIAL NOT NULL, 
	year INTEGER NOT NULL, 
	starts_on DATE NOT NULL, 
	ends_on DATE NOT NULL, 
	is_current BOOLEAN DEFAULT 'false' NOT NULL, 
	CONSTRAINT pk_academic_year PRIMARY KEY (id), 
	CONSTRAINT uq_academic_year_year UNIQUE (year)
);
CREATE TABLE subject (
	id SERIAL NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	specialty VARCHAR(60), 
	marks BOOLEAN DEFAULT 'false' NOT NULL, 
	CONSTRAINT pk_subject PRIMARY KEY (id), 
	CONSTRAINT uq_subject_name UNIQUE (name)
);
CREATE TABLE "user" (
	id SERIAL NOT NULL, 
	dni VARCHAR(32), 
	email VARCHAR(320) NOT NULL, 
	name VARCHAR(120), 
	surname VARCHAR(120), 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_user PRIMARY KEY (id), 
	CONSTRAINT ck_user_dni_format CHECK (dni ~ '^[0-9]{7,9}$'), 
	CONSTRAINT uq_user_dni UNIQUE (dni), 
	CONSTRAINT uq_user_email UNIQUE (email)
);
CREATE TABLE course (
	id SERIAL NOT NULL, 
	name VARCHAR(20) NOT NULL, 
	specialty VARCHAR(60) NOT NULL, 
	academic_year_id INTEGER NOT NULL, 
	CONSTRAINT pk_course PRIMARY KEY (id), 
	CONSTRAINT uq_course_name_academic_year_id UNIQUE (name, academic_year_id), 
	CONSTRAINT fk_course_academic_year_id FOREIGN KEY(academic_year_id) REFERENCES academic_year (id)
);
CREATE TABLE term (
	id SERIAL NOT NULL, 
	academic_year_id INTEGER NOT NULL, 
	kind term_kind NOT NULL, 
	starts_on DATE NOT NULL, 
	ends_on DATE NOT NULL, 
	CONSTRAINT pk_term PRIMARY KEY (id), 
	CONSTRAINT uq_term_academic_year_id_kind UNIQUE (academic_year_id, kind), 
	CONSTRAINT uq_term_id_academic_year_id UNIQUE (id, academic_year_id), 
	CONSTRAINT fk_term_academic_year_id FOREIGN KEY(academic_year_id) REFERENCES academic_year (id)
);
CREATE TABLE offering (
	id SERIAL NOT NULL, 
	subject_id INTEGER NOT NULL, 
	term_id INTEGER NOT NULL, 
	name VARCHAR(120), 
	kind offering_kind NOT NULL, 
	CONSTRAINT pk_offering PRIMARY KEY (id), 
	CONSTRAINT uq_offering_id_term_id UNIQUE (id, term_id), 
	CONSTRAINT fk_offering_subject_id FOREIGN KEY(subject_id) REFERENCES subject (id), 
	CONSTRAINT fk_offering_term_id FOREIGN KEY(term_id) REFERENCES term (id)
);
CREATE TABLE student_course (
	id SERIAL NOT NULL, 
	student_id INTEGER NOT NULL, 
	course_id INTEGER NOT NULL, 
	CONSTRAINT pk_student_course PRIMARY KEY (id), 
	CONSTRAINT uq_student_course_student_id_course_id UNIQUE (student_id, course_id), 
	CONSTRAINT fk_student_course_student_id FOREIGN KEY(student_id) REFERENCES "user" (id), 
	CONSTRAINT fk_student_course_course_id FOREIGN KEY(course_id) REFERENCES course (id)
);
CREATE TABLE offering_course (
	id SERIAL NOT NULL, 
	offering_id INTEGER NOT NULL, 
	course_id INTEGER NOT NULL, 
	CONSTRAINT pk_offering_course PRIMARY KEY (id), 
	CONSTRAINT uq_offering_course_offering_id_course_id UNIQUE (offering_id, course_id), 
	CONSTRAINT fk_offering_course_offering_id FOREIGN KEY(offering_id) REFERENCES offering (id), 
	CONSTRAINT fk_offering_course_course_id FOREIGN KEY(course_id) REFERENCES course (id)
);
CREATE TABLE teacher_offering (
	id SERIAL NOT NULL, 
	teacher_id INTEGER NOT NULL, 
	offering_id INTEGER NOT NULL, 
	CONSTRAINT pk_teacher_offering PRIMARY KEY (id), 
	CONSTRAINT uq_teacher_offering_teacher_id_offering_id UNIQUE (teacher_id, offering_id), 
	CONSTRAINT fk_teacher_offering_teacher_id FOREIGN KEY(teacher_id) REFERENCES "user" (id), 
	CONSTRAINT fk_teacher_offering_offering_id FOREIGN KEY(offering_id) REFERENCES offering (id)
);
CREATE TABLE student_offering (
	id SERIAL NOT NULL, 
	student_id INTEGER NOT NULL, 
	course_id INTEGER NOT NULL, 
	offering_id INTEGER NOT NULL, 
	CONSTRAINT pk_student_offering PRIMARY KEY (id), 
	CONSTRAINT uq_student_offering_student_id_offering_id UNIQUE (student_id, offering_id), 
	CONSTRAINT enrolled_via FOREIGN KEY(student_id, course_id) REFERENCES student_course (student_id, course_id), 
	CONSTRAINT eligible FOREIGN KEY(offering_id, course_id) REFERENCES offering_course (offering_id, course_id)
);

-- `public.enrollment`, itself a view. Taken verbatim from tic-auth's
-- ENROLLMENT_VIEW_SQL rather than re-derived: two copies of the mandatory/optional
-- union is exactly the logic campus owns no roster in order not to keep.
CREATE VIEW enrollment AS
    SELECT sc.student_id,
           oc.course_id,
           oc.offering_id,
           'mandatory'::offering_kind AS via
      FROM student_course sc
      JOIN offering_course oc ON oc.course_id = sc.course_id
      JOIN offering o         ON o.id = oc.offering_id
     WHERE o.kind = 'mandatory'
    UNION ALL
    SELECT so.student_id,
           so.course_id,
           so.offering_id,
           'optional'::offering_kind AS via
      FROM student_offering so;

CREATE SCHEMA directory;

-- The contract views, verbatim from tic_auth/models/contract.py.
CREATE VIEW directory."user" AS
    SELECT u.id,
           u.dni,
           u.email,
           u.name,
           u.surname,
           u.is_active
      FROM public."user" u;
CREATE VIEW directory.course AS
    SELECT c.id,
           c.name,
           c.specialty,
           c.academic_year_id,
           ay.year,
           ay.is_current
      FROM public.course c
      JOIN public.academic_year ay ON ay.id = c.academic_year_id;
CREATE VIEW directory.subject AS
    SELECT s.id,
           s.name,
           s.specialty,
           s.marks
      FROM public.subject s;
CREATE VIEW directory.offering AS
    SELECT o.id,
           o.subject_id,
           o.term_id,
           o.name,
           o.kind,
           t.kind AS term_kind,
           t.academic_year_id,
           ay.year,
           ay.is_current
      FROM public.offering o
      JOIN public.term t           ON t.id = o.term_id
      JOIN public.academic_year ay ON ay.id = t.academic_year_id;
CREATE VIEW directory.enrollment AS
    SELECT e.student_id,
           e.course_id,
           e.offering_id,
           e.via
      FROM public.enrollment e;
CREATE VIEW directory.teacher_offering AS
    SELECT t.id,
           t.teacher_id,
           t.offering_id
      FROM public.teacher_offering t;
CREATE VIEW directory.offering_course AS
    SELECT oc.id,
           oc.offering_id,
           oc.course_id
      FROM public.offering_course oc;
